# Generated by Django 5.0.2 on 2024-04-08 03:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestart', models.DateTimeField()),
                ('timeend', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='fullName',
            field=models.CharField(default='Default Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='admission_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='condition_type',
            field=models.CharField(default='Default Condition', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='full_name',
            field=models.CharField(default='Default Name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='severity',
            field=models.CharField(default='Base Severity', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(default='Default Status', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='day',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schedule',
            name='minute',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schedule',
            name='month',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='year',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surgeon',
            name='exp',
            field=models.CharField(default='Sr', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surgeon',
            name='qualifications',
            field=models.CharField(default='Sr', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaners', models.ManyToManyField(to='core.cleaner')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
                ('surgeons', models.ManyToManyField(to='core.surgeon')),
                ('time_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.time')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='assignments',
            field=models.ManyToManyField(to='core.surgery'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='surgeries',
            field=models.ManyToManyField(to='core.surgery'),
        ),
        migrations.AddField(
            model_name='employee',
            name='availability',
            field=models.ManyToManyField(related_name='available_employees', to='core.time'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sched',
            field=models.ManyToManyField(related_name='scheduled_employees', to='core.time'),
        ),
    ]
