# Generated by Django 5.0.2 on 2024-04-08 03:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_time_employee_fullname_patient_admission_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='day',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='minute',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='month',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='year',
        ),
        migrations.AddField(
            model_name='schedule',
            name='time',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='core.time'),
            preserve_default=False,
        ),
    ]
