# Generated by Django 5.0.2 on 2024-04-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_schedule_day_remove_schedule_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
